source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'sqlite3'
gem 'spring', group: :development
gem 'raddocs', :github => "smartlogic/raddocs"
gem 'rails-i18n', '~> 4.0.0'

group :test, :development do
  gem 'rspec-rails'
  gem 'rspec_api_documentation', '4.7.0'
  gem 'apidoc_to_gfm', :path => "../"
end
